### ISSUE TITLE
Recipes are extremely odd on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [AmarokIce/PineappleDelight#10]
![image](https://github.com/AmarokIce/PineappleDelight/assets/5614902/c3e5d3da-562d-4407-8e5d-11d07ffd5433)

Some of these appear to be related to tags for both knives and milk.

![image](https://github.com/AmarokIce/PineappleDelight/assets/5614902/ec063b94-7cbb-44bf-aec9-02e1c5ee0658)

![image](https://github.com/AmarokIce/PineappleDelight/assets/5614902/b8c7c3c9-0b65-457b-9e1f-1b5a91c50668)

![image](https://github.com/AmarokIce/PineappleDelight/assets/5614902/8814bdb4-7412-45da-886b-5cfe13adbba0)

Try adding support for these tags

@AmarokIce

**Comment by Sunconure11** [comment]
https://github.com/AmarokIce/PineappleDelight/pull/11

**Comment by AmarokIce** [comment]
Thanks for your help!

**Comment by Sunconure11** [comment]
Make sure these go to the Fabric/Quilt builds @AmarokIce, as this PR simply fixes the recipes there
