### ISSUE TITLE
Crash with new version

### ISSUE THREAD

**Issue by AikaBack** [AmarokIce/PineappleDelight#12]
[crash-2024-01-31_20.38.31-server.txt](https://github.com/AmarokIce/PineappleDelight/files/14113768/crash-2024-01-31_20.38.31-server.txt)
[2024-01-31-1.log.gz](https://github.com/AmarokIce/PineappleDelight/files/14113781/2024-01-31-1.log.gz)

**Comment by evertn** [comment]
Same here, though I think this issue should have a little update:

**Minecraft version:** 1.20.1
**Forge version:** 47.2.1
**Mod version:** 1.08

One of the players on the server was just planting Pineapple seeds. After a while the server suddenly crashed.

**Crash report:** https://pastebin.com/jQmFnsC8

**Comment by senlin114514** [comment]
Same Problem

**Comment by AmarokIce** [comment]
try with 1.0.11

**Comment by AmarokIce** [comment]
A problem in check season compatible, will fix, thanks for report
