### ISSUE TITLE
In version 1.0.8 bug

### ISSUE THREAD

**Issue by Flechazo098** [AmarokIce/PineappleDelight#17]
![e9dae427848da355447bb2744a4439df](https://github.com/AmarokIce/PineappleDelight/assets/173535514/9c1c9672-a66a-48ed-9c35-a48409e040fd)
In version 1.0.8, the mod's Chinese translation became invalid, and the pineapple texture turned into a block.

**Comment by AmarokIce** [comment]
will fix
