### ISSUE TITLE
Crash with mc 1.19.2 and pineappleDelight 1.0.7

### ISSUE THREAD

**Issue by Zershyan** [AmarokIce/PineappleDelight#18]
An error was reported when the MC tried to generate a chunk.
![image](https://github.com/user-attachments/assets/27a47291-6e0a-48eb-a985-06cca766532a)
The error is reported because a snowy plains is generating. I'm guessing it's due to the creation of some kind of plant or mineral.
![屏幕截图 2024-07-26 043910](https://github.com/user-attachments/assets/ace5f6fa-05c5-4e8b-a828-c35f76d408ee)
So I used [Cyanide](https://www.bilibili.com/read/cv26011548/), and after that the error showed:
![屏幕截图 2024-07-26 045505](https://github.com/user-attachments/assets/1ea76f5f-b57a-4f4e-9526-d5b6407eec9e)
Is it because I've added too many mods？
If not, can this be solved？

forge 43.4.0
mc 1.19.2
pineappleDelight 1.0.7
and other mods

**Comment by Zershyan** [comment]
This should help you with this.
[https://forge.gemwire.uk/wiki/Biome_Modifiers#Best_Practices](https://forge.gemwire.uk/wiki/Biome_Modifiers#Best_Practices)

**Comment by AmarokIce** [comment]
If here any crash-report (or log) with bin-paste or driver, I think we can solve these problems. Of course, if you do have solved the problem, please ignore this comment.
