### ISSUE TITLE
一个很严重的bug

### ISSUE THREAD

**Issue by Zershyan** [AmarokIce/PineappleDelight#19]
forge官方开发文档提到：
![image](https://github.com/user-attachments/assets/866aefd3-0282-4e69-ae27-db64546b9578)
凤梨乐事中的内容：
![image](https://github.com/user-attachments/assets/bd6555a8-cbba-4257-bf7e-8d8abfde5420)
参考果园乐事：
![image](https://github.com/user-attachments/assets/2918b40c-d00d-4cc4-a0d6-339ec7c4155a)

mod的写法导致了它兼容性极差
原因是使用了原版的生物群系
请求尽快修复，，，

**Comment by Linearpast** [comment]
[forge官方文档链接](https://forge.gemwire.uk/wiki/Biome_Modifiers#Best_Practices)

**Comment by AmarokIce** [comment]
首先我不认为这是一个**很严重**的 **Bug**。如果它确实导致了任何崩溃，请提供错误报告，错误报告和发生错误时释出的日志是真正解决问题的东西。
另外，`原因是使用了原版的生物群系` 是说不通的。即便是果园乐事，此处使用的是**标签**而不是**自创群系**。
以及一个很重要的一点，凤梨乐事采用的顺序适配器是来自农夫乐事提供的适配器。如果凤梨乐事如此危险，那么这份 Issue 很显然应该提交给农夫乐事，而不是凤梨乐事。
以及重要的一点，请不要**直接机翻文档**，很显然开头的那段话在机翻之下有很多种理解方式，但显然文档原意是指**因为修饰器可以额外注入原本写入群系 Json 内的特性，那么这会导致特性会重复。如果通过修饰器注入了原本原版就已经存在的特性，那么就会因为这相同的特性被反复执行而导致崩溃**。

这份 Issue 将会关闭，因为它没有意义。如果你对此依然有任何问题，请重新启用这份 Issue 并追加 Comment。

**Comment by Zershyan** [comment]
十分抱歉，经过我又一段时间的排查，真正的错误源应该是巫师乐事（Wizardy delight），原因未知，由于未仔细了解Cyanide mod的特性而导致的误判，您的mod是个很好的mod，它没有任何问题！
至于标题写的很严重的bug，因为它的导致的崩溃使得不管是pcl还是崩溃优化（Not Enough Crashes）都无法获取到崩溃源，这花费了我大量的时间去排查它，我反而认为有明确报错源的bug是比较轻的bug
实在是不好意思
