### ISSUE TITLE
[Bug] Pineapple Crate Display Error

### ISSUE THREAD

**Issue by TheShadyyOneYT** [AmarokIce/PineappleDelight#20]
I don't know if this is a bug for Crates Delight or Pineapples Delight, but it's a visual bug:

### Versions:
Fabric Modloader: 0.16.2
Fabric API: 0.92.2
Pineapple Crate: 1.0.11
Game Version: 1.20.1

![2024-08-25_00 16 35](https://github.com/user-attachments/assets/0977879e-a09b-4036-b7ab-c7f520ac01d3)

**Comment by AmarokIce** [comment]
will fix

**Comment by TheShadyyOneYT** [comment]
> will fix

Sweet thanks, forgot to post logs, but thank you
