### ISSUE TITLE
I can't harvest from naturally generated pineapples.

### ISSUE THREAD

**Issue by kuretoshi** [AmarokIce/PineappleDelight#22]
Even with bare hands or any tool, the item doesn't drop, and the pineapple just disappears.

**Comment by AmarokIce** [comment]
Minecraft Version, Modloader and PineappleDelight Version?

**Comment by kuretoshi** [comment]
Minecraft Version：1.21.1
ModLoader：NeoForge 21.1.61
PineappleDelight Version：1.0.0-1.21.1-forge

**Comment by AmarokIce** [comment]
Thanks for report!
Now fix it

**Comment by kuretoshi** [comment]
The pineapple saplings are now dropping. Thank you!
