### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by katubug** [AmarokIce/PineappleDelight#4]
I am having an issue where textures for growing pineapples are broken. I see that you posted a fix in the comments of the mod, but can you please fix the file on Curseforge? When a modpack uses your mod, it downloads the version off of curseforge, so any changes I make to the mod on my end do not get sent to my users.

![2023-06-22_13 02 17](https://github.com/AmarokIce/PineappleDelight/assets/20935286/86a73801-d1f8-47f7-a221-507d2af6ce93)

**Comment by AmarokIce** [comment]
Is that forge or fabric?

**Comment by katubug** [comment]
Forge 43.2.8

**Comment by AmarokIce** [comment]
Fixed it! Thanks for report this, and now file is processing in curseforge

**Comment by katubug** [comment]
Thank you!

**Comment by Sunconure11** [comment]
I saw some similar issues on the Fabric build @AmarokIce
