### ISSUE TITLE
Error during server setup //在服务器启动中出现问题

### ISSUE THREAD

**Issue by fly6516** [AmarokIce/PineappleDelight#5]
There was a problem during server startup, the problem did not appear during the use of the client, the crash did not appear after removing this mod, the problem was reproduced in the case of only the pre-installation installation, hope for help, thanks.
//
在服务器启动过程中出现问题，该问题在客户端使用过程中没有出现，删除该mod后未出现该崩溃，在仅安装前置情况下该问题得到复现，希望得到帮助，感谢。

Logs below  (all mods)
[latest.log](https://github.com/AmarokIce/PineappleDelight/files/11945683/latest.log)

Logs below  (only fabric-api,farmers delight and pineapple delight)
[latest.log](https://github.com/AmarokIce/PineappleDelight/files/11945720/latest.log)

**Comment by AmarokIce** [comment]
Fixed, a render method was erase but the server had try to run it. Now the render will run in Client only.
Thanks for report!

完成，服务器正尝试访问一个被擦除的渲染方法。现在渲染仅在逻辑客户端执行。
感谢反馈！

**Comment by fly6516** [comment]
thanks XD
