### ISSUE TITLE
[SUGGESTION] Fabric Seasons compat

### ISSUE THREAD

**Issue by Sunconure11** [AmarokIce/PineappleDelight#6]
Since pineapples are tropical plants, and well... this mod just centers around one crop, this should be easy to do.

**Comment by Sunconure11** [comment]
@AmarokIce

**Comment by AmarokIce** [comment]
Ok, I'll have try

**Comment by Sunconure11** [comment]
https://github.com/AmarokIce/PineappleDelight/pull/11

Can you go over this, as well, @AmarokIce, and see if it works?
